plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://abstracting-machine.github.io
baseurl: /qrog

title: Abstracting Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Abstracting-Machine
  verb: Abstracting
  instructions_file: abstracting.md
  token: qrog
  server: https://localhost:443
  apiUrl: https://api.groq.com/openai/v1/chat/completions
  fallback_llm: llama-3.3-70b-versatile

app:
  worker_name: qrogapi.js

lm:
  model: moonshotai/kimi-k2-instruct-0905
  max_completion_tokens: 16384
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95


github_settings:
  owner: abstracting-machine
  repo: abstracting_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
